[package]
name = "test_saori"
version = "0.1.0"
edition = "2021"

[dependencies]
encoding_rs = "0.8.34"
regex = "1.10.6"

[dependencies.windows]
version = "0.58.0"
features = [
    "Win32_System_Memory",
]

[lib]
crate-type = ["cdylib"]
